//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int id_client { get; set; }
        public string name { get; set; }
        public string web_page { get; set; }
        public string direccion { get; set; }
        public string tel { get; set; }
        public string puesto { get; set; }
    }
}
