//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReunion
    {
        public int id_reunion { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> fecha_y_hora { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<bool> esVirtual { get; set; }
        public Nullable<int> id_client { get; set; }
    }
}
