//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupport_Tickets
    {
        public int id_Support_Tickets { get; set; }
        public string title { get; set; }
        public string detalle { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_client { get; set; }
        public string estado { get; set; }
    }
}
